version: '3'
services:
  db:
    image: mysql:5.6.51
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/sample
      - public-data:/sample/public
      - tmp-data:/sample/tmp
      - log-data:/sample/log
    depends_on:
      - db

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/sample/public
      - tmp-data:/sample/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data: