development:
  adapter: mysql2
  encoding: utf8mb4
  chaeset: utf8mb4
  collation: utf8mb4_general_ci
  database: sample_development
  pool: 5
  username: sample-user
  password: sample-password
  host: localhost

test:
  adapter: mysql2
  encoding: utf8mb4
  chaeset: utf8mb4
  collation: utf8mb4_general_ci
  database: sample_test
  pool: 5
  username: sample-user
  password: sample-password
  host: localhost

production:
  adapter: mysql2
  encoding: utf8mb4
  chaeset: utf8mb4
  collation: utf8mb4_general_ci
  database: sample
  pool: 5
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock