development:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  database: sample_development
  pool: 5
  username: root
  password: root-password
  host: db

test:
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: user
  port: 3306
  host: 127.0.0.1
  database: ci_test

production:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  database: sample
  pool: 5
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock