development:
  adapter: mysql2
  encoding: utf8mb4
  chaeset: utf8mb4
  collation: utf8mb4_general_ci
  database: sample_development
  pool: 5
  username: sample-user
  password: sample-password
  host: localhost

test:
  adapter: mysql2
  encoding: utf8mb4
  chaeset: utf8mb4
  collation: utf8mb4_general_ci
  database: sample_test
  pool: 5
  username: sample-user
  password: sample-password
  host: localhost

production:
  adapter: mysql2
  encoding: utf8mb4
  chaeset: utf8mb4
  collation: utf8mb4_general_ci
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>