development:
  adapter: mysql2
  encoding: utf8
  database: sample_development
  pool: 5
  username:sample-user
  password:sample-password
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: sample_test
  pool: 5
  username:sample-user
  password:sample-password
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: sample_production
  pool: 5
  username:sample-user
  password:sample-password
  host: localhost